[package]
name = "npm_scripts"
version = "0.1.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
failure = "0.1.1"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
